
export const Theme = {
    PRIMARY: '#215DAA',
    TEXT_PRIMARY_BLACK: '#262626',
    TEXT_PRIMARY: '#215DAA',
    BACKGROUND_PRIMARY: '#F8FAFB',
    ICONS_PRIMARY: '#E8E8E8',
    MENU_ICONS_ACTIVE: '#FFFFFF',
    SECONDARY: '#83CFA4',
    DISABLED_TEXT: "#676767",
    PRIMARY_BORDER: "#BEBEBE",
    TEXT_WHITE: '#FFFFFF',
    GREEN_BORDER_COLOR: "#83CFA4",
    WHITE_BACKGROUND: "#FFFFFF",
    ERROR_TEXT: "#EE5252",
    SUCCESS: "green",
    DANGER: "#E05243",
}